version: "3.7"
services:
  api:
    container_name: api
    hostname: api
    ports:
    - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - DEBUG=true
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ['npm', 'start']
    depends_on:
      - redis
  subscriber:
    container_name: subscriber
    hostname: subscriber
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=true
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ['npm', 'run', 'startsub']
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
